default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  # username: kevin
  # password: Sashimi6/

development:
  <<: *default
  database: "brothers_wolff_development"

test:
  <<: *default
  database: "brothers_wolff_test"

production:
  <<: *default
  database: "brothers_wolff_production"